### ISSUE TITLE
Not detecting events

### ISSUE THREAD

**Issue by fredtux** [objective-see/OverSight#20]
I've uninstalled the previous version and did a fresh install of version 2.0.0 on MacOS 11.4
There are a few issues I've encountered and I'm not sure how to fix them:

1. There is no indication when the microphone is being used. I get a notification a few seconds after it became inactive
2. There is no indication for webcam usage.

And obviously I see no logs. There is no ~/Library/Application Support/Objective-See/ directory.

How can I get more information in order to trace the cause of this issue?

**Comment by bendalton** [comment]
I too am having the same issue on 11.4 on an M1 mac

`Filtering the log data using "subsystem == "com.objective-see.oversight""
Timestamp                       Thread     Type        Activity             PID    TTL
2021-07-23 15:17:52.880678-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] started: /Applications/OverSight.app/Contents/MacOS/OverSight (pid: 25563 / uid: 501)
2021-07-23 15:17:52.881356-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] arguments: (
    "/Applications/OverSight.app/Contents/MacOS/OverSight"
)
2021-07-23 15:17:52.986784-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] (real) parent: <private>
2021-07-23 15:17:52.999382-0400 0x10395e4  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] permission to display notifications granted? 1 (error: (null))
2021-07-23 15:17:53.071063-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] setting state to: enabled
2021-07-23 15:17:53.071428-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] starting AV monitoring
2021-07-23 15:17:53.071451-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] CPU architecuture: M1, will leverage 'appleh13camerad'
2021-07-23 15:17:53.071596-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] starting audio monitor
2021-07-23 15:17:53.175005-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Bitgapp/eqMac
2021-07-23 15:17:53.175027-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Creative Technology Ltd/Sound Blaster X3
2021-07-23 15:17:53.175038-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Unknown Manufacturer/C922 Pro Stream Webcam
2021-07-23 15:17:53.175045-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Immersed Inc./Immersed
2021-07-23 15:17:53.175149-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] Apple mic not found, defaulting to default (id: 55)
2021-07-23 15:17:53.175376-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] monitoring 55 for audio changes
2021-07-23 15:18:02.217704-0400 0x1039705  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new tcc access msg: SEND: 0/7 synchronous to com.apple.tccd.system: request: msgID=668.49, function=TCCAccessRequest, service=kTCCServiceMicrophone, target_token={pid:24699, auid:501, euid:501},
2021-07-23 15:18:02.220310-0400 0x1039705  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new (audio) client: CLIENT: pid: 24699, path: /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/91.0.4472.164/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper, clientID: (null)
2021-07-23 15:18:02.235357-0400 0x1039705  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new client tccd response : RECV: synchronous reply <dictionary: 0x102ff5610> { count = 4, transaction: 0, voucher = 0x0, contents =
	"auth_value" => <uint64: 0xa73a6edb5d475e87>: 2
	"result" => <bool: 0x1f8a45e70>: true
	"auth_reason" => <uint64: 0xa73a6edb5d475e97>: 0
	"auth_version" => <uint64: 0xa73a6edb5d475e9f>: 1
}
2021-07-23 15:18:02.783834-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] checking if built-in mic is active
2021-07-23 15:18:02.784056-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Bitgapp/eqMac
2021-07-23 15:18:02.784088-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Creative Technology Ltd/Sound Blaster X3
2021-07-23 15:18:02.784115-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Unknown Manufacturer/C922 Pro Stream Webcam
2021-07-23 15:18:02.784134-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] device: Immersed Inc./Immersed
2021-07-23 15:18:02.784276-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] Apple mic not found, defaulting to default (id: 55)
2021-07-23 15:18:02.784722-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] mic is not on...
2021-07-23 15:18:25.933228-0400 0x1039a3a  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] checking for update
2021-07-23 15:18:26.074191-0400 0x1039a3a  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] latest version: 1.0.0
2021-07-23 15:18:26.074285-0400 0x10395d6  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] no updates available
2021-07-23 15:18:47.799900-0400 0x1039b74  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new tcc access msg: SEND: 0/7 synchronous to com.apple.tccd.system: request: msgID=668.50, function=TCCAccessRequest, service=kTCCServiceMicrophone, target_token={pid:25665, auid:501, euid:501},
2021-07-23 15:18:47.802482-0400 0x1039b74  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new (audio) client: CLIENT: pid: 25665, path: /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/91.0.4472.164/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper, clientID: (null)
2021-07-23 15:18:47.836575-0400 0x1039b74  Debug       0x0                  25563  0    OverSight: [com.objective-see.oversight:application] new client tccd response : RECV: synchronous reply <dictionary: 0x1032f2200> { count = 4, transaction: 0, voucher = 0x0, contents =
	"auth_value" => <uint64: 0xa73a6edb5d475e87>: 2
	"result" => <bool: 0x1f8a45e70>: true
	"auth_reason" => <uint64: 0xa73a6edb5d475e97>: 0
	"auth_version" => <uint64: 0xa73a6edb5d475e9f>: 1
}`

**Comment by NicoloLazzaroni** [comment]
Same issue, running OverSight V2.0.0 on MacOS 12.0 Beta.

**Comment by YouRik** [comment]
I just installed OverSight 2.0.0 on my 2021 MBP with M1 Pro Chip on MacOS 12.0.1 and I have the same issue.
Notifications for Oversight are allowed, but none are displayed when an application accesses the camera or microphone. Only after closing the application, I then get a banner saying "Video Device became inactive."


Just like fredtux, I do not have the "~/Library/Application Support/Objective-See/" directory on my system

**Comment by notDavid** [comment]
Same issue here, OverSight installs successfully (had to install with `sudo`), but no notifications whatsoever when using a Webcam;

OverSight 2.0.1
macOS 12.1
Macbook Pro M1

**Comment by YouRik** [comment]
I just installed OverSight again and for me it is now fixed, presumably due to 0b3f6f18ac2c70855acbf92cd027f6f7d7e8e1dd. I am also now on macOS 12.1.

notDavid, have you made sure to enable notifications?

**Comment by harryfear** [comment]
Confirmed for me also; working again latest Oversight with macOS 12.1  :)

**Comment by notDavid** [comment]
Strange, it's not working for me, i start FaceTime and get no notification. I have Notifications enabled, and also running a script with the OverSight "execute action" option does not work either.

I just uninstalled, re-installed, and rebooted.

1. If it's working for you, are you running as a user with 'Admin' or 'Standard' permissions in macOS? (System Preferences > Users & Groups > Current user). I'm running as a 'Standard' user.
2. Should there be a System Daemon running for OverSight? ( i don't see any on my system)

**Comment by YouRik** [comment]
1. Yes, my User does have Admin permissions. Also, I installed OverSight through Homebrew and it asked me for my password during that installation process.
2. Using Activity Monitor I can see a running process called OverSight.

**Comment by manualmanul** [comment]
I've noticed that OverSight only notifies me about microphone access, not webcam access. Any way to fix this?

M1 Mac mini, macOS 12.2, OverSight 2.0.1

**Comment by egorgam** [comment]
I use Airpods for doing some calls. And there are no any notifications in versions 1.2.0 and 1.2.1. Maybe OverSight works only with integrated camera and microphone on macbook pro?

**Comment by YouRik** [comment]
Yes, for me it also only works for the integrated camera and microphone. Previously (as per my previous post), it did not work for those either.

**Comment by notDavid** [comment]
2.0.1 is still not working for me, for example in FaceTime.

I just installed and older version, `VERSION 1.2.0`, and now it works...

macOS 12.1
Macbook Pro M1

**Comment by gymate-1** [comment]
I have the same problem on 2.0.0 and 2.0.1.

- Device: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- OS: macOS 12.2.1

**Comment by notDavid** [comment]
Oversight does not work if you don't have `Admin` permissions... you can install and will get no error or warning messages whatsoever, but it simply does not work / show any notifications.

**Comment by gymate-1** [comment]
@notDavid My Mac user account does have admin permissions.

**Comment by freakstar50** [comment]
Using Oversight V2.0.1 on a MBP 2021 M1 Pro with a normal user account and it doesnt detect andy webcam or mic usage... when i change it to admin rights it does detect it! please fix this, dont wanna run my main account on admin rights

**Comment by objective-see** [comment]
Yes, an admin account is needed, due to the mechanism that OverSight uses to monitor for mic/webcam access.
I'll clarify this in documentation and make the code detect/alert about this better too.

**Comment by objective-see** [comment]
Also, I've just released v2.1.0: https://github.com/objective-see/OverSight/releases/download/v2.1.0/OverSight_2.1.0.zip


Though it still requires an admin account, it restore lost alerting functionality (that was broken due to changes by Apple on recent versions of macOS). If you can give it a try to let me know everything is now working that would be great! 🙏

**Comment by craikpyke** [comment]
Tried v2.1.0, still seeing the same behaviour. Account is local admin and I've installed from the installer zip linked above. I see the following:
`2022-11-26 11:32:24.283241-0500 0xcc4f     Debug       0x0                  7329   0    OverSight: [com.objective-see.oversight:application] permission to display notifications granted? 1 (error: (null))`

**Comment by frank-stonybrook** [comment]
Thanks for making such a great software! I tried 
1. **Oversight v2.0.2 on Mac Catalina (10.15.7)**. The camera and microphone monitor function seem works only if I haven't grant the software permission via Mac's privacy pop-up. Once I granted, oversight doesn't alert anymore. Also the log directory, **~/Library/Application Support/Objective-See/OverSight/OverSight.log**, does not exist; 
2. **Oversight v2.1.3 on Mac Monterey (12.6)**. Everything works like a charm! 

So I am wondering whether the Oversight v2.0.2 could be patched, since I need to use Catalina (10.15.7) and  can only install up to v2.0.2.

Thanks!

**Comment by rafaelmaeuer** [comment]
I installed OverSight v2.1.5 today on M1 Macbook with Monterey 12.6.2, no alerts are showing up wether on activating webcam or microphone...? Alerts are allowed in macOS settings...

**Comment by gurple** [comment]
Like rafaelmaeuer's observation above I am not seeing alerts nor rules being populated with v2.1.5 running on Ventura 13.2.1 (22D68). When activating FaceTime or Teams calls the mic and camera function as if Oversight isn't installed at all.

I've tried uninstalling, digging through the ~/Library/ directory for any file with the insensitive strings of objective-see and oversight and re-installing all to no avail.

**Comment by rafaelmaeuer** [comment]
I am getting all the events now, don't remember if I had to do a full restart, but its working...
